services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - supervision_network

  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - supervision_network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supervision
      MYSQL_USER: supervision
      MYSQL_PASSWORD: supervisiondb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - supervision_network

volumes:
  db_data:

networks:
  supervision_network:
    driver: bridge