<div class="container">
  <ul>
    <li>
      操作性の向上
      <ul>
        <li>ExcelからのTSVコピペに対応（複数行・複数列）</li>
      </ul>
    </li>
    <li>
      案件進行管理機能
      <ul>
        <li>ページごとの進捗管理（WBSっぽい何か）</li>
        <li>meta等のHTML出力機能</li>
      </ul>
    </li>
    <li>
      サイトマップ機能
      <ul>
        <li>親子関係の設定</li>
        <li>クロールによる自動生成</li>
        <li>サイトマップからディレクトリマップの作成</li>
        <li>ページにアイコン追加</li>
        <li>複数ページへの対応</li>
        <li>sitemap.xmlの作成</li>
        <li>サイトマップ出力機能</li>
        <li>サイトマップPDF出力機能</li>
      </ul>
    </li>
    <li>
      ワイヤーフレームの管理機能
      <ul>
        <li>ワイヤーフレーム作成機能</li>
        <li>ワイヤーフレームのアップロード機能</li>
        <li>ワイヤーフレームへのコメント機能</li>
      </ul>
    </li>
    <li>
      デザインデータの管理機能
      <ul>
        <li>デザインデータのアップロード機能</li>
        <li>デザインデータへのコメント機能</li>
        <li>ページごとの進捗管理（WBSっぽい何か）</li>
      </ul>
    </li>
    <li>
      テスト機能
      <ul>
        <li>キャプチャベースのリグレッションテスト</li>
        <li>SeleniumGridによる各ブラウザテスト</li>
        <li>Prettier等での書き方指摘(HTML/CSS/JS)</li>
        <li>スピードテスト</li>
        <li>W3C CSS Validation</li>
        <li>パス記述方法（相対/ルート相対/絶対）チェック</li>
        <li>禁止用語チェック</li>
        <li>表記揺れチェック</li>
        <li>本番環境とテスト環境の差異チェック</li>
      </ul>
    </li>
    <li>
      サービス公開するための機能追加
      <ul>
        <li>ユーザー管理機能(外部ログイン前提)</li>
        <li>リポジトリ連携(CI/CD)</li>
      </ul>
    </li>
  </ul>
</div>
